#!/usr/bin/env python3
"""Dependency-free Gmail and Google Calendar CLI for Hermes.

Uses only Python's standard library and the authorized-user token generated by
the repository's Google Workspace OAuth workflow.
"""

from __future__ import annotations

import argparse
import base64
import json
import os
import re
import sys
import tempfile
import urllib.error
import urllib.parse
import urllib.request
from datetime import datetime, timedelta, timezone
from email.message import EmailMessage
from html.parser import HTMLParser
from pathlib import Path
from typing import Any, Iterable

GMAIL_API = "https://gmail.googleapis.com/gmail/v1"
CALENDAR_API = "https://www.googleapis.com/calendar/v3"
DEFAULT_TOKEN_URI = "https://oauth2.googleapis.com/token"


def fail(message: str, *, details: Any | None = None) -> "NoReturn":
    payload: dict[str, Any] = {"error": message}
    if details is not None:
        payload["details"] = details
    print(json.dumps(payload, ensure_ascii=False), file=sys.stderr)
    raise SystemExit(1)


def config_dir() -> Path:
    explicit = os.environ.get("HERMES_CONFIG_DIR")
    if explicit:
        return Path(explicit).expanduser().resolve()

    hermes_home = os.environ.get("HERMES_HOME")
    if hermes_home:
        candidate = Path(hermes_home).expanduser().resolve()
        return candidate if candidate.name == ".hermes" else candidate / ".hermes"

    return Path.home() / ".hermes"


CONFIG_DIR = config_dir()
TOKEN_PATH = CONFIG_DIR / "google_token.json"


def load_json(path: Path) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        fail(f"Missing Google OAuth token: {path}")
    except (OSError, json.JSONDecodeError) as exc:
        fail(f"Could not read Google OAuth token: {exc}")
    if not isinstance(value, dict):
        fail("Google OAuth token must be a JSON object")
    return value


def write_private_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.parent.chmod(0o700)
    fd, temporary_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    temporary_path = Path(temporary_name)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            json.dump(payload, handle, indent=2, sort_keys=True)
            handle.write("\n")
        temporary_path.chmod(0o600)
        os.replace(temporary_path, path)
        path.chmod(0o600)
    finally:
        temporary_path.unlink(missing_ok=True)


def parse_expiry(value: Any) -> datetime | None:
    if not isinstance(value, str) or not value.strip():
        return None
    text = value.strip().replace("Z", "+00:00")
    try:
        parsed = datetime.fromisoformat(text)
    except ValueError:
        return None
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)
    return parsed.astimezone(timezone.utc)


def token_is_fresh(payload: dict[str, Any]) -> bool:
    token = payload.get("token")
    expiry = parse_expiry(payload.get("expiry"))
    return bool(token and expiry and expiry > datetime.now(timezone.utc) + timedelta(seconds=60))


def refresh_token(payload: dict[str, Any]) -> dict[str, Any]:
    required = ("refresh_token", "client_id", "client_secret")
    missing = [name for name in required if not payload.get(name)]
    if missing:
        fail("Stored Google token cannot be refreshed", details={"missing": missing})

    body = urllib.parse.urlencode(
        {
            "grant_type": "refresh_token",
            "refresh_token": payload["refresh_token"],
            "client_id": payload["client_id"],
            "client_secret": payload["client_secret"],
        }
    ).encode("ascii")
    request = urllib.request.Request(
        str(payload.get("token_uri") or DEFAULT_TOKEN_URI),
        data=body,
        headers={"Content-Type": "application/x-www-form-urlencoded"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            result = json.loads(response.read().decode("utf-8"))
    except urllib.error.HTTPError as exc:
        response_body = exc.read().decode("utf-8", errors="replace")
        try:
            details = json.loads(response_body)
        except json.JSONDecodeError:
            details = response_body
        fail("Google OAuth token refresh failed", details=details)
    except (OSError, json.JSONDecodeError) as exc:
        fail(f"Google OAuth token refresh failed: {exc}")

    access_token = result.get("access_token")
    if not access_token:
        fail("Google OAuth refresh response contained no access_token", details=result)

    payload["token"] = access_token
    expires_in = int(result.get("expires_in") or 3600)
    payload["expiry"] = (
        datetime.now(timezone.utc) + timedelta(seconds=expires_in)
    ).isoformat()
    if result.get("scope"):
        payload["scopes"] = str(result["scope"]).split()
    if result.get("token_type"):
        payload["token_type"] = result["token_type"]
    write_private_json(TOKEN_PATH, payload)
    return payload


def access_token(*, force_refresh: bool = False) -> str:
    payload = load_json(TOKEN_PATH)
    if force_refresh or not token_is_fresh(payload):
        payload = refresh_token(payload)
    token = payload.get("token")
    if not token:
        fail("Stored Google token has no access token")
    return str(token)


def api_request(
    method: str,
    url: str,
    *,
    query: dict[str, Any] | None = None,
    body: dict[str, Any] | None = None,
    retry_auth: bool = True,
) -> Any:
    if query:
        encoded = urllib.parse.urlencode(query, doseq=True)
        url = f"{url}?{encoded}"
    data = None
    headers = {
        "Authorization": f"Bearer {access_token()}",
        "Accept": "application/json",
    }
    if body is not None:
        data = json.dumps(body).encode("utf-8")
        headers["Content-Type"] = "application/json"

    request = urllib.request.Request(url, data=data, headers=headers, method=method)
    try:
        with urllib.request.urlopen(request, timeout=60) as response:
            raw = response.read()
            if not raw:
                return None
            return json.loads(raw.decode("utf-8"))
    except urllib.error.HTTPError as exc:
        response_body = exc.read().decode("utf-8", errors="replace")
        if exc.code == 401 and retry_auth:
            refresh_token(load_json(TOKEN_PATH))
            return api_request(
                method,
                url.split("?", 1)[0],
                query=query,
                body=body,
                retry_auth=False,
            )
        try:
            details = json.loads(response_body)
        except json.JSONDecodeError:
            details = response_body
        fail(
            f"Google API request failed with HTTP {exc.code}",
            details=details,
        )
    except (OSError, json.JSONDecodeError) as exc:
        fail(f"Google API request failed: {exc}")


def output(value: Any) -> None:
    print(json.dumps(value, ensure_ascii=False, indent=2))


def header_map(headers: Iterable[dict[str, Any]]) -> dict[str, str]:
    result: dict[str, str] = {}
    for item in headers:
        name = str(item.get("name") or "").lower()
        if name:
            result[name] = str(item.get("value") or "")
    return result


def decode_b64url(value: str) -> bytes:
    padding = "=" * (-len(value) % 4)
    return base64.urlsafe_b64decode((value + padding).encode("ascii"))


class _HTMLTextExtractor(HTMLParser):
    def __init__(self) -> None:
        super().__init__()
        self.parts: list[str] = []

    def handle_data(self, data: str) -> None:
        if data.strip():
            self.parts.append(data.strip())

    def text(self) -> str:
        return "\n".join(self.parts)


def html_to_text(value: str) -> str:
    parser = _HTMLTextExtractor()
    try:
        parser.feed(value)
        return parser.text()
    except Exception:
        return re.sub(r"<[^>]+>", " ", value)


def extract_message_body(payload: dict[str, Any]) -> tuple[str, str]:
    plain_parts: list[str] = []
    html_parts: list[str] = []

    def walk(part: dict[str, Any]) -> None:
        mime_type = str(part.get("mimeType") or "")
        data = ((part.get("body") or {}).get("data") or "")
        if data:
            try:
                text = decode_b64url(str(data)).decode("utf-8", errors="replace")
            except Exception:
                text = ""
            if mime_type == "text/plain":
                plain_parts.append(text)
            elif mime_type == "text/html":
                html_parts.append(text)
        for child in part.get("parts") or []:
            if isinstance(child, dict):
                walk(child)

    walk(payload)
    if plain_parts:
        return "\n\n".join(plain_parts).strip(), "text/plain"
    if html_parts:
        html = "\n\n".join(html_parts).strip()
        return html_to_text(html), "text/html"
    return "", str(payload.get("mimeType") or "")


def gmail_message_metadata(message_id: str) -> dict[str, Any]:
    encoded_id = urllib.parse.quote(message_id, safe="")
    message = api_request(
        "GET",
        f"{GMAIL_API}/users/me/messages/{encoded_id}",
        query={
            "format": "metadata",
            "metadataHeaders": ["From", "To", "Subject", "Date", "Message-ID", "Reply-To"],
        },
    )
    headers = header_map(((message.get("payload") or {}).get("headers") or []))
    return {
        "id": message.get("id"),
        "threadId": message.get("threadId"),
        "from": headers.get("from", ""),
        "to": headers.get("to", ""),
        "subject": headers.get("subject", ""),
        "date": headers.get("date", ""),
        "messageIdHeader": headers.get("message-id", ""),
        "replyTo": headers.get("reply-to", ""),
        "snippet": message.get("snippet", ""),
        "labelIds": message.get("labelIds") or [],
        "internalDate": message.get("internalDate"),
    }


def gmail_search(args: argparse.Namespace) -> None:
    maximum = max(1, min(int(args.max_results), 500))
    messages: list[dict[str, Any]] = []
    page_token: str | None = None

    while len(messages) < maximum:
        remaining = maximum - len(messages)
        query: dict[str, Any] = {
            "q": args.query,
            "maxResults": min(remaining, 500),
        }
        if page_token:
            query["pageToken"] = page_token
        result = api_request("GET", f"{GMAIL_API}/users/me/messages", query=query)
        for item in result.get("messages") or []:
            messages.append(gmail_message_metadata(str(item["id"])))
            if len(messages) >= maximum:
                break
        page_token = result.get("nextPageToken")
        if not page_token:
            break

    output(messages)


def gmail_get(args: argparse.Namespace) -> None:
    encoded_id = urllib.parse.quote(args.message_id, safe="")
    message = api_request(
        "GET",
        f"{GMAIL_API}/users/me/messages/{encoded_id}",
        query={"format": "full"},
    )
    payload = message.get("payload") or {}
    headers = header_map(payload.get("headers") or [])
    body, source_mime_type = extract_message_body(payload)
    output(
        {
            "id": message.get("id"),
            "threadId": message.get("threadId"),
            "from": headers.get("from", ""),
            "to": headers.get("to", ""),
            "cc": headers.get("cc", ""),
            "subject": headers.get("subject", ""),
            "date": headers.get("date", ""),
            "messageIdHeader": headers.get("message-id", ""),
            "snippet": message.get("snippet", ""),
            "labelIds": message.get("labelIds") or [],
            "body": body,
            "sourceMimeType": source_mime_type,
        }
    )


def build_email_message(
    *,
    to: str,
    subject: str,
    body: str,
    html: bool,
    from_value: str | None,
) -> EmailMessage:
    message = EmailMessage()
    message["To"] = to
    message["Subject"] = subject
    if from_value:
        message["From"] = from_value
    if html:
        message.set_content(html_to_text(body) or "HTML message")
        message.add_alternative(body, subtype="html")
    else:
        message.set_content(body)
    return message


def raw_message_payload(message: EmailMessage) -> str:
    return base64.urlsafe_b64encode(message.as_bytes()).decode("ascii").rstrip("=")


def gmail_send(args: argparse.Namespace) -> None:
    message = build_email_message(
        to=args.to,
        subject=args.subject,
        body=args.body,
        html=args.html,
        from_value=args.from_value,
    )
    result = api_request(
        "POST",
        f"{GMAIL_API}/users/me/messages/send",
        body={"raw": raw_message_payload(message)},
    )
    output(result)


def gmail_reply(args: argparse.Namespace) -> None:
    original = gmail_message_metadata(args.message_id)
    recipient = original.get("replyTo") or original.get("from")
    if not recipient:
        fail("Could not determine reply recipient")
    subject = str(original.get("subject") or "")
    if not subject.lower().startswith("re:"):
        subject = f"Re: {subject}"
    message = build_email_message(
        to=str(recipient),
        subject=subject,
        body=args.body,
        html=args.html,
        from_value=args.from_value,
    )
    message_id_header = str(original.get("messageIdHeader") or "")
    if message_id_header:
        message["In-Reply-To"] = message_id_header
        message["References"] = message_id_header
    result = api_request(
        "POST",
        f"{GMAIL_API}/users/me/messages/send",
        body={
            "raw": raw_message_payload(message),
            "threadId": original.get("threadId"),
        },
    )
    output(result)


def gmail_labels(_: argparse.Namespace) -> None:
    result = api_request("GET", f"{GMAIL_API}/users/me/labels")
    output(result.get("labels") or [])


def split_labels(values: list[str] | None) -> list[str]:
    labels: list[str] = []
    for value in values or []:
        labels.extend(part.strip() for part in value.split(",") if part.strip())
    return labels


def gmail_modify(args: argparse.Namespace) -> None:
    encoded_id = urllib.parse.quote(args.message_id, safe="")
    result = api_request(
        "POST",
        f"{GMAIL_API}/users/me/messages/{encoded_id}/modify",
        body={
            "addLabelIds": split_labels(args.add_labels),
            "removeLabelIds": split_labels(args.remove_labels),
        },
    )
    output(result)


def calendar_list(args: argparse.Namespace) -> None:
    now = datetime.now(timezone.utc)
    start = args.start or now.isoformat()
    end = args.end or (now + timedelta(days=7)).isoformat()
    maximum = max(1, min(int(args.max_results), 2500))
    result = api_request(
        "GET",
        f"{CALENDAR_API}/calendars/primary/events",
        query={
            "timeMin": start,
            "timeMax": end,
            "singleEvents": "true",
            "orderBy": "startTime",
            "maxResults": maximum,
        },
    )
    output(result.get("items") or [])


def calendar_create(args: argparse.Namespace) -> None:
    event: dict[str, Any] = {
        "summary": args.summary,
        "start": {"dateTime": args.start},
        "end": {"dateTime": args.end},
    }
    if args.location:
        event["location"] = args.location
    if args.description:
        event["description"] = args.description
    if args.attendees:
        event["attendees"] = [
            {"email": email.strip()}
            for email in args.attendees.split(",")
            if email.strip()
        ]
    result = api_request(
        "POST",
        f"{CALENDAR_API}/calendars/primary/events",
        body=event,
    )
    output(result)


def calendar_delete(args: argparse.Namespace) -> None:
    event_id = urllib.parse.quote(args.event_id, safe="")
    api_request(
        "DELETE",
        f"{CALENDAR_API}/calendars/primary/events/{event_id}",
    )
    output({"deleted": True, "eventId": args.event_id})


def check(_: argparse.Namespace) -> None:
    profile = api_request("GET", f"{GMAIL_API}/users/me/profile")
    events = api_request(
        "GET",
        f"{CALENDAR_API}/calendars/primary/events",
        query={
            "timeMin": datetime.now(timezone.utc).isoformat(),
            "singleEvents": "true",
            "maxResults": 1,
        },
    )
    output(
        {
            "authenticated": True,
            "emailAddress": profile.get("emailAddress"),
            "messagesTotal": profile.get("messagesTotal"),
            "calendarReachable": isinstance(events.get("items"), list),
            "runtime": "python-stdlib",
        }
    )


def parser() -> argparse.ArgumentParser:
    root = argparse.ArgumentParser(description=__doc__)
    services = root.add_subparsers(dest="service", required=True)

    services.add_parser("check", help="Verify Gmail and Calendar access")

    gmail = services.add_parser("gmail")
    gmail_commands = gmail.add_subparsers(dest="gmail_command", required=True)

    search = gmail_commands.add_parser("search")
    search.add_argument("query")
    search.add_argument("--max", dest="max_results", type=int, default=10)
    search.set_defaults(handler=gmail_search)

    get_message = gmail_commands.add_parser("get")
    get_message.add_argument("message_id")
    get_message.set_defaults(handler=gmail_get)

    send = gmail_commands.add_parser("send")
    send.add_argument("--to", required=True)
    send.add_argument("--subject", required=True)
    send.add_argument("--body", required=True)
    send.add_argument("--html", action="store_true")
    send.add_argument("--from", dest="from_value")
    send.set_defaults(handler=gmail_send)

    reply = gmail_commands.add_parser("reply")
    reply.add_argument("message_id")
    reply.add_argument("--body", required=True)
    reply.add_argument("--html", action="store_true")
    reply.add_argument("--from", dest="from_value")
    reply.set_defaults(handler=gmail_reply)

    labels = gmail_commands.add_parser("labels")
    labels.set_defaults(handler=gmail_labels)

    modify = gmail_commands.add_parser("modify")
    modify.add_argument("message_id")
    modify.add_argument("--add-labels", action="append")
    modify.add_argument("--remove-labels", action="append")
    modify.set_defaults(handler=gmail_modify)

    calendar = services.add_parser("calendar")
    calendar_commands = calendar.add_subparsers(dest="calendar_command", required=True)

    list_events = calendar_commands.add_parser("list")
    list_events.add_argument("--start")
    list_events.add_argument("--end")
    list_events.add_argument("--max", dest="max_results", type=int, default=100)
    list_events.set_defaults(handler=calendar_list)

    create_event = calendar_commands.add_parser("create")
    create_event.add_argument("--summary", required=True)
    create_event.add_argument("--start", required=True)
    create_event.add_argument("--end", required=True)
    create_event.add_argument("--location")
    create_event.add_argument("--description")
    create_event.add_argument("--attendees")
    create_event.set_defaults(handler=calendar_create)

    delete_event = calendar_commands.add_parser("delete")
    delete_event.add_argument("event_id")
    delete_event.set_defaults(handler=calendar_delete)

    return root


def main() -> None:
    args = parser().parse_args()
    if args.service == "check":
        check(args)
        return
    handler = getattr(args, "handler", None)
    if handler is None:
        fail("No command selected")
    handler(args)


if __name__ == "__main__":
    main()
